import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AnnounceBox from '../components/AnnounceBox.jsx'
import AdBanner from "../components/AdBanner.jsx"
import BoardsBox from "../components/BoardsBox.jsx"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.doc}>
        <div className={styles.hd}>
          <div className={styles.logo}>
            <a href="/">
              <Image src="/img/logo-transparent.png" height="120" width="300" />
            </a>
          </div>
        </div>
        <div className={styles.bd}>
          <AnnounceBox></AnnounceBox>
          <AdBanner></AdBanner>
          <BoardsBox></BoardsBox>
        </div>
      </div>
    </div>
  )
}
